# Generated by Django 4.2.1 on 2023-08-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lname', models.CharField(blank=True, max_length=120)),
                ('phone', models.IntegerField()),
                ('date', models.DateField()),
                ('address', models.CharField(default='Indore madhyapradesh', max_length=120)),
            ],
        ),
    ]
